[package]
name = "cyrcle-agent"
version = "0.1.0"
edition = "2021"
authors = ["Sam"]
description = """"""
readme = "../Readme.md"
keywords = ["gpg-agent", "auth"]
license = "GPL-3"
publish = false
#default-run = "cyrcle-agent"

# [[bin]]
# name = "cyrcle-agent"

[dependencies] 